name: Test Chapter 05_04
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          cd Ch05/05_04-challenge-build-an-nginx-container-image
          docker --version
          docker build --progress plain --tag binaryville .
          docker run --detach --rm --publish 443:443 --name binaryville binaryville
      
      - name: Wait
        run: until [ $(curl -o /dev/null --silent --head --write-out '%{http_code}\n' -Lk https://localhost/) -eq 200 ]; do echo -n '.'; sleep 1; done
      
      - name: Test
        run: curl -sLk https://localhost/ | grep "Welcome to Binaryville"
      
      - name: Stop
        run: docker stop binaryville
