name: Test Chapter 05_04
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          cd Ch05/05_04-challenge-build-an-nginx-container-image
          docker --version
          docker build --tag binaryville .
          docker run --detach --rm --publish 443:443 --name binaryville binaryville
      
      - name: Wait-Non-Windows
        if: runner.os != 'Windows'
        run: until [ $(curl -o /dev/null --silent --head --write-out '%{http_code}\n' -Lk https://localhost/) -eq 200 ]; do echo -n '.'; sleep 1; done
      
      - name: Test-Non-Windows
        if: runner.os != 'Windows'
        run: curl -sLk https://localhost/ | grep "Welcome to Binaryville"
      
      - name: Stop
        run: docker stop binaryville
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
